### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by younesStrittmatter**
fix links

### CODE REVIEW

**Review by benwandrew — APPROVED** [review]

**Comment by hollandjg** [comment]
The images are still missing for the sampler, right? I guess we'd need to duplicate them from the other directory, or use a relative link like `../pooler/mse.png`

**Comment by younesStrittmatter** [comment]
yes

**Comment by benwandrew** [comment]
i’m not sure about the entire index.md file for the pooler. it looks like that which is in the pooler directory is written for the sampler. @musslick should there be different content for the pooler (with or without the same mse.png and model-vs-data.png files)?

**Comment by benwandrew** [comment]
only the top paragraph has been updated to read for the pooler

**Review by hollandjg — APPROVED** [review]
Hi @younesStrittmatter – should we just get this merged, and worry about the test errors later? There’s already the issue #8 for that

**Pull request merged**
